name = "edge-og-worker"
main = "src/index.ts"
compatibility_date = "2025-07-26"

# NOTE: This TOML is the single source of truth for Wrangler config in dev.
# We intentionally removed wrangler.jsonc to avoid conflicting settings that
# can force remote preview mode or OAuth prompts. Use `pnpm dev` which runs
# `wrangler dev --local` to ensure a stable, Miniflare-only environment.

[dev]
ip = "127.0.0.1"
port = 8787

[[kv_namespaces]]
binding = "TEMPLATES"
id = "⚙️ prod_id"
preview_id = "⚙️ dev_id"

[[kv_namespaces]]
binding = "USAGE"
id = "⚙️ usage_id"
preview_id = "⚙️ usage_preview_id"

[[kv_namespaces]]
binding = "ACCOUNTS"
id = "⚙️ accounts_id"
preview_id = "⚙️ accounts_preview_id"

[vars]
BASE_URL = "https://edge-og-worker.edge-og.workers.dev"

# Ensure HTML imports are bundled as text
[[rules]]
type = "Text"
globs = ["**/*.html"]